export const initialData = [
  {
    img: "lake-inniscarra-thumb.jpg",
    imgAlt: "Lake Inniscarra, Ireland--Pyramid",
    avatarAlt: "profile picture",
    avatar: "lake-inniscarra-trainer.jpg",
    heading: "Lake Inniscarra, Ireland--Pyramid",
    time: "30:53",
    miles: "6,248 MI",
    videoCt: "",
  },
  {
    img: "performance-series-thumb.jpg",
    imgAlt: "Performance Series",
    avatarAlt: "profile picture",
    avatar: "performance-series-trainer.jpg",
    heading: "Performance Series",
    time: "",
    miles: "",
    videoCt: "9",
  },
  {
    img: "slow-pulls-thumb.jpg",
    imgAlt: "Slow Pulls and Fast Intervals",
    avatarAlt: "profile picture",
    avatar: "slow-pulls-trainer.jpg",
    heading: "Slow Pulls and Fast Intervals",
    time: "44:13",
    miles: "9,948 MI",
    videoCt: "",
  },
  {
    img: "20-minutes-to-toned-thumb.jpg",
    imgAlt: "20 Minutes to Toned",
    avatarAlt: "profile picture",
    avatar: "20-minutes-to-toned-trainer.jpg",
    heading: "20 Minutes to Toned",
    time: "",
    miles: "",
    videoCt: "12",
  },
  {
    img: "charles-race-thumb.jpg",
    imgAlt: "Charles Race, Boston, Massachusetts",
    avatarAlt: "profile picture",
    avatar: "charles-race-trainer.jpg",
    heading: "Charles Race, Boston, Massachusetts",
    time: "36:22",
    miles: "8,648 MI",
    videoCt: "",
  },
  {
    img: "full-body-hiit-thumb.jpg",
    imgAlt: "Full-Body HIIT Series",
    avatarAlt: "profile picture",
    avatar: "full-body-hiit-trainer.jpg",
    heading: "Full-Body HIIT Series",
    time: "",
    miles: "",
    videoCt: "12",
  },
  {
    img: "kafue-river-thumb.jpg",
    imgAlt: "Kafue River, Zambia-- Power Stroke Pyramid",
    avatarAlt: "profile picture",
    avatar: "kafue-river-trainer.jpg",
    heading: "Kafue River, Zambia-- Power Stroke Pyramid",
    time: "22:22",
    miles: "4,660 MI",
    videoCt: "",
  },
  {
    img: "shred-and-burn-thumb.jpg",
    imgAlt: "Shred & Burn Series",
    avatarAlt: "profile picture",
    avatar: "shred-and-burn-trainer.jpg",
    heading: "Shred & Burn Series",
    time: "",
    miles: "",
    videoCt: "16",
  },
];
